name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          any-of-labels: 'Wait for reply'
          stale-pr-message: 'The PR is stale and will be closed in 5 days'
          stale-pr-label: 'Stale'
          days-before-stale: 1 #30
          days-before-close: 1 #5
